DROP TABLE IF EXISTS android_metadata;
CREATE TABLE android_metadata (locale TEXT);
INSERT INTO android_metadata (locale) VALUES ('en_GB');
DROP TABLE IF EXISTS CASTLE;
CREATE TABLE CASTLE (ID INTEGER PRIMARY KEY AUTOINCREMENT,INFO TEXT,IMG TEXT,IMG_SM TEXT,LAT REAL,LNG REAL,TITLE TEXT,VIDEO TEXT,INFO_EN TEXT,TITLE_EN TEXT);
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (1, 'Kalaja e Beratit eshte ngritur në një kodër 187 metra të lartë, në të majtë të grykës së lumit Osum. Fillimisht, një vendbanim protourban, në shekullin e VII-V p.e.s, si një pikë strategjike e rëndesishme, ajo u shndërrua në qytet kështjellë me mure që arrinin në gjatësi deri në 1.400 metra dhe me një sipërfaqe prej 10 ha. 
  Burimet historike deshmojne se prej këtij viti kalaja e Beratit ka qenë objekt i sulmeve të ndryshme.Në dokumenta të ndryshme historike të kohës gjenden një sërë emrash. Me emrin e lashte Antipatrea përmendet në vitin 216 p.e.s.. Nga romakët u quajt edhe Albanorum oppidium (fortesa e Arberve).Një nga monumentet më të bukur, më të mëdha dhe më të rëndësishëm të historisë dhe kulturës shqiptare është padyshim kalaja e Beratit. 
 Me formën e saj të spikatur në trajtë trekëndëshi ajo ngrihet mbi një kodër të lartë 187 m, e cila ndodhet në bregun e djathtë të lumit Osum, duke dominuar luginën e tij (Hëna Spahiu, Qyteti Iliro-Arbëror i Beratit. Tiranë 1990, fq. 9-11). Në të kaluarën siguria e kësaj kështjelle ka qënë maksimale, sepse projektuesit e saj e ndërtuan pikërisht në këtë kodër ku ana jugore bie thikë mbi Osum, anët lindore dhe perëndimore kanë pjerrësi të madhe ndërsa në anën veriore kodra ulet ëmbël drejt qafës së Biftës, duke siguruar komunikimin. Muret kanë një perimetër prej 1400 m brinja lindore e këtij trekëndëshi është e gjatë 620 m ndërsa dy tjerat janë të barabarta dhe janë të gjata 410 m (Berati, Historia dhe arkitektura Tiranë 1988, fq. 34). 
Ndryshe nga kështjellat e tjera kalaja e Beratit ka qenë e pajisur me 24 kulla të cilat emërtohen sot me emrin turk TABJE së bashku me muret ato i përkasin periudhave të ndryshme të ndërtimit që nisin qysh nga shekulli IV Pk dhe përfundojnë gjatë kohës së sundimit të Ali Pashë Tepelenës (1813-1821). Brenda sipërfaqes prej 9.6 ha të kalasë ndodhen disa kisha, një pjesë e të cilave rrënojë, Sarajet turke, rrënojat e dy xhamive, sternat e ujit të quajtura Saranxha, sheshi i Sallabandës, sheshi i quajtur fusha e madhe etj.
 Ndërkohë që pjesën më të madhe të këtij oborrit të brendshëm e zënë një sërë rrugicash, kopshtesh, bacesh dhe shtëpi banimi të cilat përbëjnë lagjen e quajtur kala. Gjithsej ky monument ka katër porta komunikimi. Njëra prej tyre dhe pikërisht ajo që paraqet më shumë interes për shkak të elementeve përbërës të saj është ato e anës juglindore. 
Pasi kalon në të futesh në një oborr të fortifikuar, ku përpara të del një portë e dytë pikërisht në murin ballor të saj, në anën e djathtë të një harku (Apollon Baçe, qyteti i fortifikuar i Beratit, Monumentet 2, 1971, fq.43-63), ndodhet një monogram me tulla të kuqe që i përket ndërtimeve bizantine të vitit 1204. I ndërtuar ashtu si i gjithë kompleksi mbrojtës nga Despoti i Epirit Mihal I Porta me monogramin në formë kryqi me inicialet M.K. edhe sot ruan po këtë emër “Porta e Mihal Komnenit”.', 'berati', 'berati_sm', 40.708763, 19.945592, 'Kalaja e Beratit', 'QbGkxnHUANg', 'The fortress of Berat is erected on a 187-meter-high hill, on the left side of the Osumi River slope. Initially, a protourban settlement, in the seventh century BC, as a strategic point of importance, it became a castle town with walls of up to 1,400 meters in length and 10 ha.
  Historical sources testify that this year the fortress of Berat has been the subject of various attacks. Various historical documents of the time contain a series of names. The ancient name Antipatrea is mentioned in 216 BC. The Romans were also called the Albanorum oppidium (Arberve fortress). One of the most beautiful, largest and most important monuments of Albanian history and culture is undoubtedly the fortress of Berat.
 With its prominent triangular shape, it rises above a 187m high hill, which is located on the right bank of the Osumi River, dominating its valley (Moon Spahiu, City of Iliro-Arbëror of Berat, Tirana, 1990, pg. 9-11). In the past, the security of this fort was the best because its designers built it on this hill where the south side collapsed on Osum, the eastern and western sides have a large slope while on the northern side the hill slopes sweetly towards Biftha''s neck, Secure communication. The walls have a perimeter of 1400 m long eastern bridle of this triangle is 620 m long while the other two are equal and long 410 m (Berat, History and Architecture, Tirana, 1988, p. 34).
Unlike other castles, the fortress of Berat has been equipped with 24 towers which are named today with the Turkish name TABJE together with the walls they belong to different periods of construction commencing since the IV century BC and end during the time of Ali''s rule Pash Tepelena (1813-1821). Within the area of ??9.6 ha of the castle there are several churches, some of which ruin, Turkish Sarajet, ruins of two mosques, water cranes called Saranxha, Sallabanda Square, square called big field etc.
 While most of this inner courtyard is surrounded by a series of alleys, gardens, bachets and residential houses that make up the neighborhood called the fortress. In total this monument has four communication gates. One of them and the one that presents the most interest due to its constituent elements is that of the southeastern side.
After passing through, you enter a fortified courtyard where a second gate is on the right side of an arch (Apollo Baça, Fortified City of Berat, Monument 2, 1971, p. 43-63), there is a red brick monogram belonging to the Byzantine buildings of 1204. Built as the entire defensive complex by Epirus Despot Mihal I Gate with cross-shaped monogram with initials MK Today also retains the same name "Mihal Komnen''s Gate".', 'Castle of Berat');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (2, 'Kalaja e Borshit ndodhet rreth 3 km në VP të fshatit Borsh, Sarandë. Ajo ngrihet mbi një kodër, e cila përfundon në majë me një kreshtë shkëmbore dhe zë një pozicion qendror kundrejt qytetit antik të Borshit, i cili shtrihej dikur në shpatet e kësaj kodre.
  Kalaja ka një pozitë të rëndësishme strategjike jo vetëm sepse ndodhet pranë detit por edhe pranë njërës nga dy grykat që përshkonin që në lashtësi malet Akrokeraune, në mesjetë të njohura si malet e Himarës, duke lidhur bregdetin me brendësinë e vendit. Nëpërmjet “Grykës së Borshit” realizohej lidhja me Kalasën dhe Delvinën.', 'borshi', 'borshi_sm', 40.06981, 19.856073, 'Kalaja e Borshit', 'OAlkb1CDTKA', 'Borsh Castle is about 3 km to VP of Borsh village, Saranda. It rises above a hill, which ends on top with a rocky crest and occupies a central position against the ancient city of Borsh, which once lay on the slopes of this hill.
   The castle has an important strategic position not only because it is located near the sea, but also near one of the two gorges that crossed the ancient Acroceraune mountains in the middle ages known as the Himara Mountains, linking the coast with the interior of the country. Through the "Borshi Gorge" there was a connection with the Castle and Delvina.', 'Castle of Borsh');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (3, 'Kalaja e Dajtit ndodhet në tarracën detare të Dajtit në lartësinë 1200 mbi nivelin e detit, në shpatin perëndimor të malit të Dajtit, mbi një majë në të djathtë të rrugës që të çon nga Qafa e Priskës për në fushën e Dajtit.
Mendohet se ajo mund të jetë një nga kalatë e ndërtuara nga perandori bizantin Justiniani (527- 566) dhe i përket gjysmës së shek.VI.
 Kalaja ka një sipërfaqe prej 1.12 ha, dhe në pjesën më të madhe të saj ajo është mjaft e pjerrët. Muret kanë qenë të detyruar të ndjekin formën e kodrës, duke formuar një trekëndësh i cili është forcuar në tre këndet me nga një kullë të rrumbullakët. 
Sipërfaqja e rrethuar nga këta mure është në pjesën më të madhe mjaft e pjerrët dhe e mbuluar me shkëmbinj, vetëm në rrëzë të mureve dhe pjesën midis dy majave kjo është e përshtatshme për ndërtim banesash. Trashësia e mureve është e lidhur me cilësitë mbrojtëse të terrenit, atje ku terreni është shumë i pjerrët jepte mundësi mbrojtjeje edhe një mur jo i trashë, ndërsa në vendet pak të pjerrëta ekzistonte një mur i trashë. ', 'dajti', 'dajti_sm', 41.359778, 19.915417, 'Kalaja e Dajtit', '', 'Dajti Castle is located on the Dajti seafront, 1200 feet above sea level, on the western slope of Dajti Mountain, on a top right of the road that leads from Prfa''s Neck to the Dajti field.
It is thought that it may be one of the forts built by the Byzantine emperor Justinian (527-566) and belongs to the half of the VI century.
 The castle has an area of ??1.12 ha, and for the most part it is quite steep. The walls have been forced to follow the shape of the hill, forming a triangle that is strengthened in three corners with a round tower.
The area surrounded by these walls is mostly fairly steep and covered with rocks, just at the foot of the walls and the area between the two peaks is suitable for housing construction. The thickness of the walls is related to the protective properties of the terrain, where the terrain is very steep gives protection even a thick wall, while in the slightly steep places there was a thick wall.', 'Castle of Dajt');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (4, 'Ndodhet në qytetin e Delvinës, në një pikë gjeografike që ka dominuar hyrjen nga treva e Gjirokastrës me anë të Qafës së Muzinës për në fushën e Vrinës. Kështjella ka pasur një sipërfaqe prej 0.17 ha, ngrihej mbi një kurriz shkëmbor dhe dy rrugë ngjiteshin për tek ajo nga jugu dhe veriu. Nga anët e tjera rrethohet me dy përrenj.
 Fortifikimi përbëhej prej kështjellës dhe një muri parapritë në anën perëndimore. Vetë kështjella ka pasur trajtën e një gjysmë elipsi me drejtim perëndim – lindje dhe shfrytëzonte plotësisht mbrojten natyrale të terrenit. Balli lindor i murit i kundërvihej qafës. 
 Në ekstremin perëndimor ajo mbrohej nga një kullë gjashtëkëndëshe dhe muri zgjatej në anën veriore deri te hyrjae kështjellës. Në jug muri ndjek konturin e greminës. Muri ballor pëson një thyerje dhe mbrohej prej dy kullave anësore, të cilat sëbashku me murin parapritë formojnë një kompleks mbrojtës. Mbrojtja e përgjithshme e kështjellës paraqet një rast unik për zonën.', 'delvina', 'delvina_sm', 39.946833, 20.090722, 'Kalaja e Delvines', '', 'It is located in the town of Delvina, at a geographical point that dominated the entrance from the Gjirokastra area through the neck of Muzina to the area of ??Vrina. The castle had an area of ??0.17 hectares, erected on a rocky ridge, and two roads climbed to it from the south and north. On the other side is surrounded by two streams.
 The fortification consisted of a castle and a front wall on the western side. The castles themselves have had the shape of a semi-ellipse west-east direction and fully utilized the natural defense of the terrain. The eastern wall of the wall opposed the neck.
 In the western extremity it was protected by a hexagonal tower and the wall stretched out on the north side to the entrance to the castle. In the south the wall follows the outskirts of the desert. The front wall faces a fracture and is protected by two side towers, which together with the wall precede form a protective compound. The general protection of the castle represents a unique opportunity for the area.', 'Castle of Delvina');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (5, 'Kalaja e Dorëzit ndodhet rreth 20 km në jug perëndim të Tiranës dhe rreth 5 km në lindje të Pezës. Ajo është më e vjetra në trevën e Tiranës. Kjo kala i takon shekujve IX-IV para Krishtit, ndërsa ekspedita e parë arkeologjike drejt saj është kryer në vitin 1951. Rrënojat e saj mbulojnë një nga kuotat më të larta në vargun e kodrave të shkëputura nga malet e Krrabës në lartësinë 479 m nga niveli i detit. Mendohet që këtu të ketë qenë qyteza e Dimalit antik. 
 Për ndërtimin kalasë është zgjedhur një pllajë e pjerrët ku afro gjysma nuk është e rrethuar me mur por është e mbrojtur nga shkëmbi natyral. Muri rrethues i saj, shtrihet në të gjithë pjesën jugore të një kodre shkëmbore dhe është afërsisht 300 m i gjatë, nga lindja në perëndim. 
 Kalaja e Dorëzit paraqet një interes të veçantë për nga ana e teknikës së ndërtimit ku vihen re tre faza: faza e parë e ndërtuar me gurë të papunuar, faza e dytë me blloqe të gdhendur të vendosur në të thatë (periudha helenistike) dhe e treta që ndjek të njëjtën trase me të dytën ndërtuar me gurë të thyer të lidhur me llaç (antikiteti i vone, shek. IV-VI).  Në njërën anë të mureve, mund të dallohet vendi ku duhet të ketë qenë hyrja për në kala, aty janë gjetur fragmente enësh. Fragmente muresh të tjera të një periudhe më të vonë, tregojnë e qyteti i hershëm ilir ka qenë i banuar deri në kohët e vona antike.', 'dorzi', 'dorzi_sm', 41.226275, 19.743504, 'Kalaja e Dorëzit', '', 'The castle of Dorëz is located about 20 km southwest of Tirana and about 5 km east of Peza. It is older in the Tirana area. This fortress dates back to the 9th to the 4th centuries BC, while the first archaeological expedition to it was completed in 1951. Its ruins cover one of the highest quotas in the hollow of the hills off the Krraba Mountains at 479 m above sea level Of the sea. It is thought to have been the town of ancient Dimal.
 For the castle building, a sloping plateau is chosen where nearly half is not surrounded by a wall but is protected by a natural rock. Its perimeter wall extends across the southern part of a rocky hill and is approximately 300 m long, from east to west.
 The castle of Dorza represents a special interest by the construction technique where three phases are seen: the first phase built of unpolished stone, the second phase with carved blocks set in the dry (Hellenistic period) and the third Which follows the same path with the second built with rugged stones stitched (later antiquity, IV-VI century). On one side of the walls, it can be distinguished where the entrance to the fortress should have been, where fragments of dishes were found. Other wall fragments of a later period, indicate the early Illyrian city has been inhabited until late antiquity.', 'Castle of Dorëzi');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (6, 'Kalaja e Drishtit gjendet në një distancë prej 6 km nga Ura e Mesit mbi lumin Kir. Fshati i sotëm ndodhet poshtë vendgërmimit të Drivastumit të lashtë. Ai u ngrit në periudhën romake si një vendbanim në rrugën Shkodër–Kosovë dhe në antikitetin e vonë ishte njëra prej fortesave zinxhir, të cilat mbronin Shkodrën.
 Në shek IX, Drishti u kthye në një fortifikim të rëndësishëm të Mbretërise së Zetës dhe varej nga Dioqeza e Tivarit. Kalaja e Drishtit u ngrit në shek XIII si një fortesë bizantine. Gjate shekujve XIV-XV kalaja se bashku me qytetin kaloi nga njeri sundues tek tjetri, derisa me 1478 bie ne duart e osmaneve, te cilet u perpoqen ta meremetonin. ', 'drishti', 'drishti_sm', 42.125143, 19.611873, 'Kalaja e Drishtit', '', 'The Drisht Castle is located at a distance of 6 km from the Mesar Bridge on the Kir River. Today''s village is located below the excavation site of the ancient Drivastum. It was erected in the Roman period as a settlement in the Shkodër-Kosovo road and in late antiquity was one of the chain fortresses that defended Shkodra.
  In the 9th century, Drishti turned into an important fortification of the Zeta King and depended on the Diocese of Tivari. The Castle of Drisht was built in the 13th century as a Byzantine fortress. During the 14th and 15th centuries, the castle together with the city passed from one man to the other, until in 1478 it falls into the hands of the Ottomans, who tried to repair them.', 'Castle of Drishti');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (7, 'Kalaja u ndërtua nga perandori i Perandorisë Bizantine Anastasi I cili origjinën nga Durrësi. Në atë kohë, Anastasius e bëri Durrësin një nga qytetet më të fortifikuara në Adriatik. Riparime të mureve janë kryer që prej tërmetit shkatërrimtar të vitit 1273. 
 Mureve mesjetare aktualisht rreth 4.6 metra në lartësi dhe tri hyrjet e disa prej kullave të fortifikimit janë ruajtur në gati një të tretën e gjatësisë fillestare të qytetit kala. Kalaja u përforcuar me disa kulla roje nga Republika e Venedikut dhe gjatë pushtimit të Shqipërisë nga Perandoria Osmane muret u përforcuar.
Më 7 prill 1939, patriotët shqiptarë luftuan në muret e kalasë fashistët italian që pushtuan Shqipërinë. Në Durrës, një forcë prej vetëm 360 shqiptarë, kryesisht xhandarëve dhe banorë të qytetit, të udhëhequra nga Abaz Kupi, komandant i xhandarmërisë në Durrës, dhe Mujo Ulqinaku, një zyrtar detarë, u përpoq për të ndalur përparimin e italianëve. 
 Të armatosur vetëm me armë të vogla dhe tre automatikë, ata patën sukses në mbajtjen italianët në gji për disa orë deri sa një numër i madh i tankeve të lehta zbarkuan nga anijet detare të këtij të fundit. Pas kësaj, rezistenca zvogëluar dhe brenda pesë orëve Italia kishte pushtuar të gjithë qytetin ', 'durresi', 'durresi_sm', 41.313081, 19.443839, 'Kalaja e Durrësit', ' Kp29p9_RmUA', 'The castle was built by the emperor of the Byzantine Empire Anastasios, which originated from Durres. At that time, Anastasius made Durrës one of the fortified cities in the Adriatic. Wall repairs have been carried out since the devastating earthquake of 1273.
 Medieval walls currently about 4.6 meters in height and three entrances to some of the fortification towers have been preserved in nearly one-third of the city''s initial fortress length. The castle was reinforced with several watchtowers from the Republic of Venice and during the invasion of Albania by the Ottoman Empire the walls were reinforced.
On April 7, 1939, Albanian patriots fought on the walls of the castle the Italian fascists who invaded Albania. In Durres, a force of only 360 Albanians, mostly gendarmes and residents of the city, led by Abaz Kupi, commander of the gendarmerie in Durres, and Mujo Ulqinaku, a naval officer, tried to stop the progress of the Italians.
 Armed only with small arms and three automatic weapons, they succeeded in keeping the Italians in the bay for several hours until a large number of light tanks disembarked from the naval ships of the latter. After that, the resistance diminished and within five hours Italy had invaded the entire city', 'Castle of Durrës');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (8, 'Kalaja e Gjirokastrës si histori e lidhur me qytetin e Gjirokastrës, përmendet për herë të parë si qytet dhe kështjellë në vitin 1336. Në këto vite, ajo ishte qendra e feudalëve shqiptarë Zenevisë. Më vonë, gjatë sundimit të Gjin Bue Shpatës, ajo u përfshi në Despotatin e Epirit. 
 E megjithatë historianë të ndryshëm mendojnë se ekzistenca e kalasë së gurtë është më e hershme. Sipas tyre, kalaja ka pas dy faza ndërtimi, të cilat lidhen me periudhën para dhe pas Pashallëkut të Janinës dhe fortesave të Ali Pashë Tepelenës. 
 Nga Kalaja mesjetare, ajo e para pushtimit të Ali Pashës, ruhen vetëm pak gjurmë pasi muret janë veshur deri në lartësi nga ndërtimet e reja. Ndërsa, kullat pjesërisht janë rrënuar dhe ripërshtatur. ', 'gjirokastra', 'gjirokastra_sm', 40.073796, 20.140413, 'Kalaja e Gjirokastres', 'kXg7gDgooe4', 'The Gjirokastra fortress as a history related to the city of Gjirokastra is mentioned for the first time as a town and castle in 1336. During these years it was the center of the Albanian feudal lords Zenevia. Later, during the rule of the Sword Blade, she was included in the Despotate of Epirus.
  Yet different historians think that the existence of the stone fortress is the earliest. According to them, the castle had two construction stages, which relate to the period before and after the Pasha of Ioannina and the fortresses of Ali Pasha Tepelena.
  From the medieval fortress, before the invasion of Ali Pasha, only a few footprints have been preserved as the walls have been worn to the height of the new construction. While, the towers have been partially ruined and redesigned.', 'Castle of Gjirokastra');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (9, 'Ndodhet ne fshatin Tragjas dhe është e ndërtuar ne shekullin XVI - XVII. Ka forme drejtkëndëshe me gjerësi muresh 1,25 metra dhe lartësi deri ne 5,5 metra.
              ', 'gjonbocari', 'gjonbocari_sm', 40.311125, 19.502465, 'Kalaja e Gjon Boçarit', '', 'It is located in the village of Tragjas and is built in the XVI - XVII century. It has a rectangular shape with a wall width of 1.25 meters and a height of up to 5.5 meters.', 'Castle of Gjon Boçar');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (10, ' Kalaja e Ishmit është një kala dhe monument i trashëgimisë kulturore në Ishëm, në qarkun e Durrësit, Shqipëri [1]. Ajo është ndërtuar nga viti 1572 deri në vitin 1574 nga osmanët. Përballë hyrjes së kalasë është varros artisti shqiptar Ibrahim Kodra. Nga kodra ku ngrihet kalaja është i shikueshëm gjithashtu lumi Ishëm. ', 'ishmi', 'ishmi_sm', 41.5392693, 19.5947755, 'Kalaja e Ishmit', '', 'Ishmi Castle is a fortress and monument of cultural heritage in Ishëm, Durres district, Albania [1]. It was built between 1572 and 1574 by the Ottomans. In front of the entrance of the castle is buried Albanian artist Ibrahim Kodra. From the hill where the fortress is raised, the river is also visible.', 'Castle of Ishm');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (11, ' Kalaja e Kaninës ndodhet 6 km larg nga qyteti i Vlorës. Kjo kala është përmendur që në shekullin IV. Megjithatë aty janë zbuluar gjurmë që prej periudhës ilire. Mendohet se është ndërtuar që në shek III. Gjurmë të mëpasme janë ato të periudhave bizantine, veneciane dhe turke.
 Kalaja është rindërtuar nga Justiniani në shek V dhe meremetuar nga sulltan Sulejmani më 1531. Kalaja ngrihet në majë të një kodre me lartësi 380 metra mbi nivelin e detit. Ajo ka një sipërfaqe prej 3.6 hektarësh. Prej këndej hapet një pamje mjaft e bukur drejt Vlorës dhe gjirit të saj.', 'kanina', 'kanina_sm', 40.444546, 19.521446, 'Kalaja e Kanines', '', 'The canyon of Kanin is located 6 km from the city of Vlora. This fortress has been mentioned since the IV century. However, traces have been discovered since the Illyrian period. It is believed that it was built since the 3rd century. Further traces are those of Byzantine, Venetian and Turkish periods.
  The castle was rebuilt by Justinian in the 5th century and repaired by Sultan Sulejmani in 1531. The castle rises atop a hill with a height of 380 meters above sea level. It has an area of 3.6 hectares. From here opens a beautiful view towards Vlora and its bay.', 'Castle of Kanina');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (12, 'Këlcyra e sotme është qyteza që ju njihni në rrethin e Përmetit përballë grykës së Këlcyrës, buzë bregut të djathtë të luginës së Vjosës. Por dikur ka qenë një pikë e rëndësishme kalimi, që përmendet në librat e historisë që në shek. IV-III para Krishtit.
Rreth kësaj kohe në një kodër të malit të Trebeshinit, u ngrit kështjella e Këlcyrës me mure blloqesh guri drejtkëndësh. Fortifikimet u rindërtuan në mesjetën paraosmane. Përmendet për herë të parë në dokumente të shkruara më 1272 me emrin Klausura.Rreth vitit 1335 përmendet kur e marrin kryengritësit arbëreshë. 
 Në pjesën më të lartë të kodrës qenë edhe rrënojat e një kështjelle të periudhës së pushtimit osman. Në regjistrin osman të v. 1431 shënohet si qendër e vilajetit të Këlcyrës. Gjatë periudhës së Rilindjes Kombëtare, në këtë zonë, zhvilluan veprimtari patriotike një varg atdhetarësh', 'kelcyra', 'kelcyra_sm', 40.308711, 20.18351, 'Kalaja e Këlcyres', '', 'Today''s Këlcyra is the town you know in the district of Përmet near the mouth of Këlcyra, right bank of the Vjosa valley. But it was once an important point of passage, mentioned in the history books since the nineteenth century. IV-III BC.
About this time on a hill of Trebesian mountain, the castle of Këlcyra was erected with walls of rectangular stone blocks. The fortifications were rebuilt in the pre-Ottoman Middle Ages. It is mentioned for the first time in documents written in 1272 under the name Klausura. Around 1335 is mentioned when the arbëreshë rebels take it.
  At the top of the hill were the ruins of a fortress of the Ottoman conquest. In the Ottoman register of v. 1431 is marked as the center of the vilayet of Këlcyra. During the National Renaissance period, patriotic activity was developed in this area by a series of patriots', 'Castle of Këlcyra');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (13, 'Kjo kala me trajtë eliptike dhe me perimetër 804 m, zë një sipërfaqe prej 2.5 ha tokë dhe është ngritur në një kodër shkëmbore. Gërmimet arkeologjike të vitit 1978 dëshmojnë se kodra ka qenë e banuar që në shek e III p.e.r. ndërsa kalaja është ngritur në shek. V-VI e.r. Pranë saj është zbuluar një varrezë e madhe e kulturës arbërore. 
 Përmendet me emrin e sotëm në shek e IX bashkë me qytetin e Krujës si qendër peshkopale. Në shek XIII-XIV ishte qendra e shtetit të Arbrit. Gjatë periudhës së Skënderbeut u bë krye-fortesa e qëndresës së shqiptarëve kundër pushtimit osman. Edhe në ditët e sotme është një ndër vendet më të njohura dhe më të vizituar nga turistët. ', 'kruja', 'kruja_sm', 41.50696, 19.794273, 'Kalaja e Krujes', 'ZVdWLo8qtgc', 'This elliptical and 804m-long fortress occupies an area of 2.5 ha of land and is erected on a rocky hill. Archaeological excavations of 1978 prove that the hill has been inhabited since the III century BC. While the castle was erected in the nineteenth century. V-VI e.r. Near it is discovered a great cemetery of arboreal culture.
  It is mentioned in today''s name in the 9th century together with the city of Kruja as a bishopric center. In the 13th-14th centuries, it was the center of the state of Arbër. During the Skanderbeg period became the main stronghold of the resistance of the Albanians against the Ottoman invasion. Even today it is one of the most popular and most visited places by tourists.', 'Castle of Kruja');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (14, 'Lagja kala e Himarës, ose fshati i Himarës, është ndërtuar mbi kodrën e Barbakasë. Himara përbën një qytet me histori të gjatë, e cila fillon që në periudhën antike, shek. XIII p. Kr.. Ajo është vendosur mbi një kodër ku sot ndodhet lagjja kala. Kreshta shkëmbore është fortifikuar për herë të parë në shek. XIII p. Kr. 
 Më pas ndërtohet një tjetër fortifikim në shek. V p. Kr., me mure të ndërtuar me blloqe gurësh poligonalë ndërsa në shek. IV fortifikohet me mure të tipit trapezoidalë. Në shek. IV – III p. Kr. Himara renditet midis qendrave të lulëzuara të bregdetit Akrokeraun, krahas Meandrias(Borshit).Në brendësinë e rrethimit, në anën perëndimore të rrëpirës shkëmbore, përfshiheshin dhe banesa të ndërtuara dhe të punuara pjesërisht në shkëmb. 
 Rëndësia e kësaj qendre në periudhën antike vlerësohet nëpërmjet gjetjeve të shumta arkeologjike, si objekte qeramike, maja heshtash, shpata hekuri, etj. apo edhe një mbishkrim të vitit 169 p. Kr. të zbuluar në Delf, sipas të cilit qyteti Kemarai (Himarë) dërgon tek orakulli i Delfit theorodokët (priftërinjtë), krahas qyteteve të tjera të Foinikes dhe Abanties. ', 'himara', 'himara_sm', 40.117971, 19.731692, 'Kalaja e Himares', '', 'The Himara Fortress, or the village of Himara, is built on the Barbacan hill. Himara is a city with a long history, which begins in the antiquity, c. XIII p. It is situated on a hill where today is the quay of the fortress. The rocky cliffs were fortified for the first time in the 20th century. XIII p. Kr.
 Then another fortification was built in the 18th century. V p. ., With walls built with polygonal stone blocks while in the 15th century. IV is fortified with trapezoidal walls. In the nineteenth century. IV - III p. Kr. Himara ranks among the flourishing centers of the Akrocharan coast, along with Meandrias (Borshi). Within the enclosure, on the west side of the rocky slope were included partly constructed and partially built flats.
 The importance of this center in the ancient period is valued through numerous archaeological finds such as ceramic objects, peaks, iron swords, and so on. Or even an inscription of 169 p. Kr. Discovered in Delf, according to which the city of Kemarai (Himara) sends to the oracle of Delphi theorodokët (priests), in addition to other cities of Foinike and Abanties.', 'Castle of Himara');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (15, 'Kalaja ndodhet midis rrënojave të fshati Lëkurës mbi majën e një kodre të lartë që ngrihet sipër qytetit të Sarandës. Ka një pozicion të veçantë strategjik nga ku mund të shikoni gjithë qytetin e Sarandës dhe rrugën që shkon në Butrintit, gjithashtu mund të shijoni dhe një panoramë të ishujve të Ksamilit. 
 Ka formë katrore me dy kulla të rrumbullakëta të vendosura në VP dhe JL. Katrori me dy rrumbullake ne diagonale është simboli i lëkurëpunuesve në mesjete ne këto zona. Kati i parë ka shërbyer si depo. Kuptohet nga pozicioni i vendosjes që qëllimi kryesor i ndërtimit të kalasë ishte vrojtimi i detit. Lartësia e mureve arrin 6,7-7 m trashësia e tyre deri në 2 m.  
 Sot në Lëkurës funksionon një bar-restorant me arkitekturë të hershme dhe tepër bashkëkohore, ofron një shërbim ideal. Është kthyer në një nga pikat më të bukura turistike dhe nga më të frekuentuarat për çdo turist që viziton Sarandën.Mendohet nga historianët të jetë ndërtuar rreth viteve 1537, në kohën kur Sulltan Sulejmani sulmoi Korfuzin dhe i lindi si domosdoshmëri kontrolli i Skelës së Sarandës dhe rrugës që kalon Sarandë-Butrint. ', 'lekuresi', 'lekuresi_sm', 39.866108, 20.025668, 'Kalaja e Lekuresit', '', 'The castle is located between the ruins of the village Skin on the top of a high hill that rises above the city of Saranda. There is a special strategic position where you can see the entire city of Saranda and the road that goes to Butrint, you can also enjoy a panorama of the islands of Ksamil.
 It has square shape with two round towers located in VP and JL. The two-round diagonal square is the symbol of leatherworkers in the Middle Ages in these areas. The first floor served as a repository. It is understood by the placement position that the main purpose of the castle construction was to observe the sea. The height of the walls reaches 6,7-7 m their thickness up to 2 m.
 Today in the Skin operates a restaurant bar with early architecture and incredibly contemporary, offering an ideal service. It is back to one of the most beautiful tourist spots and the most frequented for any tourist visiting Saranda. It is believed by historians to be built around 1537, when Sultan Suleiman attacked Corfu and caused Saranda Skela control as a necessity The road that pass Saranda-Butrint.', 'Castle of Lekures');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (16, 'Kalaja e Lezhës ngrihet në majë të një kodre me lartësi 186 metra, në lindje të qytetit. Kalaja ka origjinë ilire. Në vitin 1440 ajo iu nënshtrua një rindërtimi nga venedikasit, ndërsa në vitin 1522 pas pushtimit osman u rindërtua edhe nga ana e tyre. Këtu mund të shikohen gjurmë të arkitekturave ilire, romake, bizantine dhe osmane. 
 Objektet më interesante për tu vizituar janë rrënojat e ndërtesave osmane brenda kalasë, xhamia, kulla në murin juglindor me një hark romak dhe kulla ilire në murin jugor. Kalaja e Lezhës është monument kulture. Prej saj shihet një pamje mjaft e bukur e fushës së Lezhës dhe e detit Adriatik.Qyteti i ndërtuar në kodër ka një pozicion strategjik që kontrollon luginën e Drinit deri në Gjirin e Shën Gjinit në detin Adriatik', 'lezha', 'lezha_sm', 41.783994, 19.649385, 'Kalaja e Lezhes', 'O7abP6M0Nt4', 'The castle of Lezha rises on top of a hill 186 meters high, east of the city. The castle is of Illyrian origin. In 1440 it underwent a reconstruction of the Venetians, and in 1522 after the Ottoman conquest was also rebuilt by them. Here you can see traces of Illyrian, Roman, Byzantine and Ottoman architecture.
  The most interesting objects to visit are the ruins of Ottoman buildings within the castle, mosque, towers on the southeast wall with a Roman arch and Illyrian towers on the southern wall. The castle of Lezha is a cultural monument. From it you can see a beautiful view of the Lezha and Adriatic Sea. The hill town has a strategic position controlling the Drin Valley up to the Gulf of St. John in the Adriatic Sea', 'Castle of Lezha');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (17, 'Kalaja e Pogradecit është e vendosur në majën e kodrës, në pjesën perëndimore të qytetit të Pogradecit, me lartësi 205 m mbi nivelin e liqenit të Ohrit. Ka filluar të banohej që në shek. V para Krishtit, ndërsa në shek. IV para Krishtit u pajis me mure mbrojtëse. Ka pasur një vjetërsi banimi prej 1400 vjetësh, duke qenë një kala iliro - shqiptare e hershme. ', 'pogradeci', 'pogradeci_sm', 40.908583, 20.646188, 'Kalaja e Pogradecit', '', 'The Pogradec fortress is located on the top of the hill, in the western part of the city of Pogradec, with a height of 205 m above the lake level of Ohrid. It started to be inhabited since the twentieth century. BC, while in the nineteenth century. IV BC was equipped with protective walls. There has been a residential age of 1400 years, being an early Illyrian-Albanian fortress.', 'Castle of Pogradec');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (18, 'Themelet e kalasë së Peqinit mendohet se i përkasin periudhës romake, në kohën e ndërtimit të rrugës "Egnatia" dhe më pas është rikonstruktuar edhe gjatë pushtimit turk. Muret e kalasë, që mban edhe emrin e vendbanimit ilir të Klaudianës kanë pasur një lartësi prej rreth 12 metrash. Kalaja e "Klaudianës" është zgjeruar në shekullin e XIV-të nga turqit, të cilët ia dhanë më pas spahiut të kazasë, i cili ndërtoi një saraj dykatësh dhe një harem. Demir Pasha ka qenë i fundit që ka jetuar në kalanë e Peqinit. 
 Këtë fortesë e përmend në shënimet e tij edhe kronikani i shekullit të XVII-të, Çelebiu, i cili thotë : "...muret e kësaj kështjelle shkojnë rreth 12 metra të lartë. Brenda rri dizdari dhe ka 70 ushtarë. Ka 5 topa në këtë kështjellë dhe 10 shtëpi të vogla të mbuluara me tjegulla. Ka gjithashtu një xhami të vogël pa minare. Në të majtë të kështjellës ngjitur me një mur ka një namazgja...". 
 Kalaja ka qenë e pajisur me llagëme (tunele) të nëndheshme që shërbenin si dalje disa kilometra larg qytetit, në kohë të vështira. Po ashtu, në muret e kalasë janë gjetur tuba prej balte, që sipas arkeologëve do të thotë se në kohë lufte furnizimi me ujë është bërë nga jashtë. ', 'peqini', 'peqini_sm', 41.044959, 19.749711, 'Kalaja e Peqinit', 'TLNShDIyoLE', 'The foundations of the Peqin Castle are thought to belong to the Roman period, at the time of the construction of the "Egnatia" road and then were reconstructed during the Turkish invasion. The walls of the castle, also bearing the name of the Illyrian settlement of Claudius, had a height of about 12 meters. The castle of "Klaudian" expanded in the 14th century by the Turks, who later gave it to the spahiu of the brick, which built a double sarai and a harem. Demir Pasha was the last one to have lived in the Peqin Castle.
 This fortress also mentions in his notes the XVII century chronicle, Çelebiu, which says: "... the walls of this fortress are about 12 meters high, within the dizdar and there are 70 soldiers. This castle and 10 small houses covered with tiles There is also a small mosque without minarets On the left of the castle adjacent to a wall there is a prayer ... ".
 The castle was equipped with underground tunnels that served as a few miles away from the city in difficult times. Also on the walls of the castle are found earthen tubes, which according to archaeologists means that in war time water supply was made from the outside.', 'Castle of Peqin');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (19, 'Kalaja e Gurit të Bardhë apo Petralbës, siç njihet ndryshe dikur ishte një ndër selitë e Kastriotëve. Sipas historianëve zona përbënte një ndër pikat e rëndësishme nën varësinë e tyre me një popullsi jo të vogël për kohën.
Ngjitja drejt selisë së dikurshme që siç shkruan Marin Barleti frekuentohej në mënyrë të rregullt nga Donika Kastrioti, por edhe nga bashkëshorti i saj Gjergj Kastrioti Skënderbeu është një kacavirrje e vazhdueshme mes majave të thepisura. Duket e jashtëzakonshme të shohësh vendin e saj, ndoshta për këtë Barleti e cilësonte një kala të ngritur majë një mali e që s’i trembej asnjë fuqie armike, përveç urisë.  ', 'petralba', 'petralba_sm', 41.648253, 20.188444, 'Kalaja e Petralbes', '', 'The Castle of White Stone or Petralba, as it is sometimes known, was one of the Kastrioti''s headquarters. According to historians the area was one of the important points under their dependence with a not so small population for the time.
The climb to the former headquarters that, as Marin Barleti wrote, was regularly frequented by Donika Kastrioti, but also by her husband, Gjergj Kastrioti Skanderbeg, is a steady flow between the steep leaks. It seems extraordinary to see her place, perhaps for this Barletus, calling it a fortress erected on top of a mountain that does not fear any enemy power except hunger.', 'Castle of Petralba');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (20, 'KKalaja e Petrelës nga zbulimet e bëra, është kala mesjetare e ndërtuar në kohën e sundimit të Perandorit Bizantin Justianit të I, në shekullin e VI pas Krishtit. Kjo qe një prej kalave të ngritura prej tij në sistemin mbrojtës së Perandorisë.Është kala e ngritur mbi një terren me shpate mjaft të pjerrëta, madje nga ana jugore dhe juglindore të thepisura, të cilat e kanë bërë kalanë shumë të mbrojtur.  
 Ajo u ngrit në momentin kur Kalaja e Vilës, kala antike, e cila ndodhet përballë Kalasë së Petrelës, e humbi rëndësinë e saj. Ajo u ngrit kryesisht për qëllime ushtarake. Kalaja e Petrelës kontrollonte rrugën Egnatia, dega Durrës-Tiranë-Elbasan, e cila për kohën kishte rëndësi të veçantë. 
 Në fillim të shek. XIV-të ishte nën sundimin e Topiajve, në atë kohë zotërues midis Matit e Shkumbinit, në një faqe të murit ruhet dhe emblema e parë e Topiajve. ', 'petrela', 'petrela_sm', 41.25519, 19.854334, 'Kalaja e Petreles', '', 'The Petrela Castle is a medieval fortress built during the rule of Byzantine Justian I emperor in the 6th century AD. This was one of the heralds raised in the defense system of the Empire. It is a fortress erected on a terrain with quite steep slopes, even from the southeastern and south-eastern part of the coast, which have made the fortress very protected.
  It arose when the Castle of the Villa, the antique fortress, located opposite the Petrela Castle, lost its importance. It was set up primarily for military purposes. The Petrela Castle controlled the Egnatia road, the Durrës-Tirana-Elbasan branch, which for the time was of particular importance.
  At the beginning of the century. The XIV century was under the rule of Topiaj, at that time between Mat and Shkumbin, on top of a wall there is the first emblem of Topiya.', 'Castle of Petrela');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (21, 'Kalaja e vogël është e vendosur në një pozicion mjaft të bukur në një gadishull në gjirin e vogël tektonik të Porto Palermos (në antikitet e njohur si gjiri i Panormes). Kalaja ndodhet jo larg fshatit të Qeparose dhe ka formë trekëndore. Përmasat e saj janë 150 m x 400 m. Lartësia e mureve arrin në 20 m.

Kalaja e Porto Palermos ndodhet në gjirin me të njëjtin emër në bregun e detit Jon në Shqipërinë e jugut. Kalaja ndodhet mbi një ishull rreth 30 m larg bregut ku rripi i ngushtë ujor midis bregut dhe ishullit është mbushur me dhe e gurë për të realizuar një lidhje tokësore me të.

Kalaja ka formë planimetrike trekëndore me tre bastione të fuqishme nëpër qoshet. Hyrja ndodhet në mesin e murit jugor. Nga ana e detit, midis dy bastioneve një sipërfaqe në formë trapezi është rrethuar me mure të pajisura me frëngji. Pjesa tjetër e kështjellës përbëhet nga një numër i madh ambientesh të mbuluara me qemerë të cilat përfundojnë në pjesën e sipërme me një tarracë të përbashkët. Ambientet shërbenin për strehimin e garnizonit, ndërsa njeri prej tyre shërbente si burg.

Kalaja është shume me e vjetër se Ali Pashaj, ai e ka restauruar, e ka pasur ne kontroll këtë pike dhe vetëm si vizitor ka qene aty, nuk ka jetuar kurrë aty. Kishën (Shën Nikolla) nuk e ka bere ai ka qene atje, dhe gjelbërimi nuk është gjithëvjeçar ne dimër thahet.', 'portopalermo', 'portopalermo_sm', 40.062503, 19.790611, 'Kalaja e Porto Palermos ', 'qnP7hZLBZvI', 'The small castle is located in a pretty beautiful position on a peninsula in the small tectonic bay of Porto Palermo (in antiquity known as Panormes Bay). The castle is located not far from the village of Qeparose and has a triangular shape. Its dimensions are 150 m x 400 m. The height of the walls reaches 20 m.

The port of Porto Palermo is located in the bay of the same name on the Ionian Sea coast in southern Albania. The castle is located on an island about 30 m from the shore where the narrow waterline between the coast and the island is filled with stones and to realize a land connection with it.

The castle has a triangular planimetric shape with three powerful ramparts in the corners. The entrance is located in the middle of the southern wall. On the sea side, between two bastions a trapeze-shaped surface is surrounded by turret-walled walls. The rest of the castle consists of a large number of covered environments, which end up in the upper part with a shared terrace. The premises were used for sheltering the garrison, while one of them served as a prison.

The castle is far older than Ali Pashaj, he has restored it, had control of this point and only as a visitor was there, never lived there. The Church (St. Nicholas) has not done it has been there, and the greenery is not perennial in winter withers.', 'Castle of Porto Palermo ');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (22, 'Kalaja e Prezës është ndërtuar mbi një shkëmb i cili zgjatet duke u ulur në drejtim të veri-jugut. Ana lindore e kalasë është e mbrojtur nga vetë terreni, kurse ana perëndimore përbën një territor të sheshtë, prandaj dhe fortifikimi është përqendruar pikërisht në këtë pjesë.
Kalaja ka planimetri katërkëndore me brinjë 80 x 50 m. Ajo përforcohet nëpër qoshe me katër kulla që kanë planimetri rrethore. Në murin perëndimor për të përforcuar më tepër sistemin fortifikues të kalasë, pasi kjo pjesë është me e ekspozuar dhe më pak e mbrojtur ndaj sulmeve si dhe ka një largësi të konsiderueshme midis kullave, është ndërtuar një kullë katërkëndëshe e dalë nga muri. 
 Në faqen jugore është ndërtuar një kullë tjetër katërkëndëshe për të mbrojtur hyrjen e vetme të kalasë. Kjo kullë përforcohet dhe nga oborri që ndodhet në përbërje të saj. Në kala kemi katër faza të ndryshme ndërtimi. Periudha e parë lidhet me fortifikim e kalasë, e dyta lidhet me rindërtimin e mureve rrethuese, e treta ka të bëjë me ndërtimet që janë bërë brenda mureve rrethuese, kurse faza e katër lidhet me ndërtimin e një kulle sahati që nuk ka të bëjë me sistemin fortifikues, por i përket një periudhe të mëvonshme ', 'preza', 'preza_sm', 41.43156, 19.672333, 'Kalaja e Prezes', '', 'Preza Castle is built on a cliff that extends to the north-south. The eastern side of the castle is protected by the terrain itself, while the western side constitutes a flat territory, therefore the fortification is centered precisely on this part.
The castle has a quadrilateral planimeter with 80 x 50 m ribs. It is reinforced through the four-tower corner with circular planimeters. In the western wall to reinforce the fortification system of the castle, as this part is more exposed and less protected against attacks, and has a considerable distance between the towers, a quadrilateral tower is emerging from the wall.
 On the south side, another quadrangular tower was built to protect the single entrance of the castle. This tower is reinforced by the yard in its composition. At the fortress we have four different construction stages. The first period is related to the fortification of the castle, the second relates to the reconstruction of the surrounding walls, the third relates to the constructions that have been made within the surrounding walls, and the fourth phase relates to the building of a clock tower that is not related to the system Fortify, but belongs to a later period', 'Castle of Preza');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (23, 'Kalaja e Rodonit ndodhet në kepin e Rodonit. Princi Karl Topia dëshironte ta kthente këtë vend në një kantier detar, ndërsa Skënderbeu, duke synuar që të kishte një dalje të afërt në det, ngriti këtu një kështjellë. Kjo kala filloi të ngrihej mbas rrethimit të parë të Krujës në vitin 1450. Përfundimi i saj mendohet të jetë rreth vitit 1452. Muri i kështjellës së Rodonit arrinte në një gjatësi prej 400 metrash dhe në kulmet e saj kishte kulla të rumbullakëta. 
 Në vitin 1500 kalaja u pushtua nga Venediku. Si rezultat i veprimtarive erozive të ujërave të detit, një pjesë e mureve janë zhytur nën ujërat e detit Adriatik. Sot vizitorët mund të shikojnë muret e jashtme të anës së djathtë, të cilat përfundojnë me një kullë të rrumbullakët. Pranë kalasë ndodhen edhe rrënojat e Kishës së Shën Pjetrit, të cilat konsiderohen nga banorët si vend i shenjtë. ', 'rodoni', 'rodoni_sm', 41.585806, 19.44815, 'Kalaja e Rodonit ', '', 'The Rodon Castle is located on the Rodon Cape. Prince Karl Topia wanted to return this place to a shipyard, while Skanderbeg, aiming to have a near sea exit, erected a castle here. This fortress began to rise after the first siege of Kruja in 1450. Its completion is supposed to be about 1452. The wall of the castle of Rodon reached a length of 400 meters and its roofs had round towers.
  In 1500 the castle was conquered by Venice. As a result of erosive seawater activities, a part of the walls have sunk beneath the waters of the Adriatic Sea. Today visitors can see the exterior wall of the right, which ends with a round tower. Near the castle there are also ruins of St. Peter''s Church, which are considered by the inhabitants as a sanctuary.', 'Castle of Rodon');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (24, 'Kështjella e Rozafatit është e ngritur mbi një kodër shkëmbore në hyrje të qytetit të Shkodrës. Mbi faqet e pjerrëta të kodrës ngrihen muret rrethuese të cilat zenë një sipërfaqe rreth 9 ha. Në periudhën e lashtë muret ishin të stilit poligonal, gjurmë të të cilave ruhen edhe sot. Si qendër e fortifikuar ilire përmendet për herë të parë gjatë sundimit të mbretit Gent dhe historiani Tit Livi e quan "vendi më i fortë i labeatëve". 
 Kështjella del me emrin Rozafa në periudhën e mesjetës, gjatë së cilës u pushtua herë nga sllavët dhe herë nga bizantinët. Brenda mureve të saj ruhen një sërë mjedisesh si garnizone, depo, një ndërtesë administrative etj ', 'shkodra', 'shkodra_sm', 42.046536, 19.493587, 'Kalaja e Rozafes', 'DtY7wtYlZ5Q', 'The fortress of Rozafa is built on a rocky hill at the entrance of the city of Shkodra. On the sloping hillside there are raised surrounding walls that occupy an area of about 9 ha. In ancient times the walls were of polygonal style, whose traces are preserved today. As Illyrian fortified center is mentioned for the first time during the reign of King Gent and historian Tit Livi calls it the "strongest labeat place".
  The castle is named Rozafa in the Middle Ages, during which time it was occupied by Slavs and by the Byzantines. Within its walls are preserved a range of environments such as garrisons, warehouses, an administrative building, and so on', 'Castle of Rozafa');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (25, 'Kalaja e Laçit i përket si ndërtim antikitetit të vonë që mbijetoi edhe në mesjetë.

Muret e rrethimit fortifikues të kështjellës së Sebastes e cila shërbente si pikë kontrolli në rrugën Dyrrhachium-Lisus-Scodrae, bazuar në teknikën e ndërtimit me gurë kuadratikë si dhe fragmentet e qeramikës me vernik të zi të gjetura brenda saj, e datojnë atë si kala të fundit të shekullit të 4-ërt dhe fillimit të shekullit të 3-të. 
 Sipas një mbishkrimi sepulkral nga burimet antike të shek. I, ku përmendet LUPUS PARTHINUS EX LATIO, mendohet se kjo kështjellë i përket qyetit LATIUM, i cili identifikohet si vendndodhje me Laçin e sotëm.', 'sebaste', 'sebaste_sm', 41.628419, 19.727894, 'Kalaja e Sebastes', '', 'Laci Castle belongs to the late antiquity building which survived even in the Middle Ages.

The walls of the fortification fortress of the Sebastes castle, which served as a checkpoint on the Dyrrhachium-Lisus-Scodrae road, based on the quadratic stone construction technique and the black varnish pottery found inside it, date it as a fortress The end of the 4th century and the beginning of the 3rd century.
  According to a sepulchral inscription from the ancient sources of the century. Where LUPUS PARTHINUS EX LATIO is mentioned, it is believed that this fortress belongs to the LATIUM town, which is identified as the location of today''s Laç.', 'Castle of Sebasta');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (26, 'Kalaja e Ali Pashë Tepelenës ndodhet në veri të qytetit në një pozicion gjeografik që ndihmonte në mbrojtejen e kalasë. Nga burimet historike, kalaja është vizonuar nga vetë Pashai i cili ka inspektuar etapat e ndërtimit të kësaj perle të rajonit. Kalaja aktuale u rindërtua prej tij më 1819 me një siperfaqe 4-5 ha me tre hyrje dhe 3 kulla. Deri me 1820 ka qene rezidenca e dyte e Ali Pashë Tepelenës.', 'tepelena', 'tepelena_sm', 40.299623, 20.021474, 'Kalaja e Tepelenes', 'pbER0N0HkMk', 'The Ali Pasha Tepelena fortress is located in the north of the city in a geographic position that helps protect the castle. From the historical sources, the castle was dotted by Pashai himself, who inspected the construction stages of this region''s pearls. The actual castle was rebuilt by him in 1819 with a surface of 4-5 ha with three entrances and 3 towers. Until 1820 was the second residence of Ali Pasha Tepelena.', 'Castle of Tepelena');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (27, 'Kalaja e Tiranës ishte një stacion rrugor i vijës Egnatia i tipit Mansio-Mutatio. Ajo përbënte qendrën e një vendbanimi, të emërtuar me një variacion emrash që në shekujt e parë të erës sonë. Tirkan (shek IV e.s ), Tergiana (1297) kur në të ishte vendosur kancelaria e sundimtarit të saj Karli I Anzhu, dhe në formën e sotme Tyranna (1505) sipas Barletit. 
 Ky tiponim akoma nuk është saktësuar plotësisht. Por kalaja, dëshmia më e lashtë e këtij qyteti, ndodhet pikërisht në vendin ku derdheshin e kryqëzoheshin rrugët e vjetra e të reja që e lidhnin kryeqytetin dhe pastaj krejt Shqipërinë – veriun me jugun, lindjen me perëndimin. 
 Në ambientet e Kalasë së Tiranës ka disa shtëpi tradicionale të cilat kanë krijuar stilin e ndërtesës qytetare Tiranase. Në ndërtesat brenda Kalasë së Tiranës kanë banuar pjesëtarë të familjeve sunduese të qytetit dhe për këtë arsye ato konsiderohen edhe si godina të administratës së parë lokale.', 'tirana', 'tirana_sm', 41.32643, 19.82207, 'Kalaja e Tiranes', '', 'The Castle of Tirana was a Mansio-Mutatio line of Egnatia line. It was the center of a settlement, labeled with a variety of names since the first centuries of our era. Tirkan (IV century), Tergiana (1297), when the chancellery of its ruler Karli I Anzhu was established, and in today''s form Tyranna (1505) according to Barleti.
  This type is still not fully specified. But the castle, the oldest evidence of this city, is located exactly where the old and new roads connecting the capital and then all of Albania - the north to the south, the east to the west - were crossed and crossed.
  In the premises of the Castle of Tirana there are several traditional houses which have created the style of Tirana''s civic building. In the buildings within the castle of Tirana have inhabited members of the ruling families of the city and therefore they are also considered as buildings of the first local administration.', 'Castle of Tirana');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (28, 'Kalaja e Varoshit është monument kulturor i ndodhur në Ndroq , Tiranë.Ky monument kulturor i takon kategorisë arkitekturor dhe është i mbrojtur me ligj.Në dokumentet turke kjo kala njihej edhe me emrin Stelush. Kalaja e cila i përket shek.XIV është ndërtuar në një pikë strategjike mbi një majë shkëmbore të mbrojtur. Rrafshi i vogël në jug e lidhte me qytetin e poshtëm, Varoshin. 
 Zotëronte njërën nga dy rrugët kryesore që lidhnin Dibrën me Matin dhe me bregdetin e Shqipërisë. Varoshi u rindërtua dhe mori tiparet e një qyteti mesjetar kur u fuqizua principata e Kastriotëve. Skënderbeu e mori në dhjetor 1443, e përfshiu në sistemin mbrojtës të vendit dhe kështjella luajti rol në luftërat e tij.', 'varoshi', 'varoshi_sm', 41.247314, 19.648283, 'Kalaja e Varoshit', '', 'Varosh Castle is a cultural monument located in Ndroq, Tirana.This cultural monument belongs to the architectural category and is protected by law. In Turkish documents this castle was also known as Stelush. The castle belonging to the XIV century was built on a strategic point on a protected rocky peak. The small plain south connected it to the lower town of Varoshi.
  It possessed one of the two main roads connecting Dibra with Mat and the Albanian coast. Varoshi was rebuilt and acquired the features of a medieval city when the Kastrioti prince was empowered. Skanderbeg took over in December 1443, swept it into the country''s defense system, and castles played a role in his wars.', 'Castle of Varosh');
INSERT INTO CASTLE (ID, INFO, IMG, IMG_SM, LAT, LNG, TITLE, VIDEO, INFO_EN, TITLE_EN) VALUES (29, 'Kalaja e Zgërdheshit ne fshatin Zgerdhesh ne Lindje te Ures se Zeze, ne JugPerendim te fshatit Zgerdhesh, ne kuoten 252, muret dhe gjithe kodra e kufizuar nga veriu e jugu me 2 perrenjte, nga lindja me qafen dhe nga perendimi ne arat e lagjes Kakariq.', 'zgerdheshi', 'zgerdheshi_sm', 41.47575, 19.777347, 'Kalaja e Zgërdheshit', '', 'The Castle of Zgërdhesh in the village Zgerdhesh in the East of the Black Bridge, in the south of the village of Zgerdhesh, in the 252th part, the walls and all the hills limited by the north and south by 2 rivers, east by the neck and from the west in the fields of the neighborhood Kakariq.', 'Castle of Zgërdhesh');